# Generated by Django 6.0.7 on 2026-08-24 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('subject_type', models.CharField(default='listing', max_length=32)),
                ('subject_key', models.CharField(max_length=255)),
                ('initiator_id', models.UUIDField(db_index=True)),
                ('counterparty_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'classified_conversation_subject',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation_id', '-created_at'], name='classified_conv_recent')],
                'constraints': [models.UniqueConstraint(fields=('conversation_id', 'subject_type', 'subject_key'), name='uniq_conversation_subject')],
            },
        ),
    ]
